# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: echo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'echo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\necho.proto\x12\x04\x65\x63ho\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x1a\n\x0b\x45\x63hoRequest\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x1c\n\x0c\x45\x63hoResponse\x12\x0c\n\x04\x65\x63ho\x18\x01 \x01(\t\"\x1e\n\x0f\x43\x61llEchoRequest\x12\x0b\n\x03msg\x18\x01 \x01(\t\"f\n\x10\x43\x61llEchoResponse\x12\x11\n\tservice_b\x18\x01 \x01(\t\x12\x16\n\x0eservice_a_echo\x18\x02 \x01(\t\x12\x18\n\x10service_a_status\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t2C\n\rHealthService\x12\x32\n\x05\x43heck\x12\x13.echo.HealthRequest\x1a\x14.echo.HealthResponse2<\n\x0b\x45\x63hoService\x12-\n\x04\x45\x63ho\x12\x11.echo.EchoRequest\x1a\x12.echo.EchoResponse2L\n\x0f\x43\x61llEchoService\x12\x39\n\x08\x43\x61llEcho\x12\x15.echo.CallEchoRequest\x1a\x16.echo.CallEchoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'echo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHREQUEST']._serialized_start=20
  _globals['_HEALTHREQUEST']._serialized_end=35
  _globals['_HEALTHRESPONSE']._serialized_start=37
  _globals['_HEALTHRESPONSE']._serialized_end=69
  _globals['_ECHOREQUEST']._serialized_start=71
  _globals['_ECHOREQUEST']._serialized_end=97
  _globals['_ECHORESPONSE']._serialized_start=99
  _globals['_ECHORESPONSE']._serialized_end=127
  _globals['_CALLECHOREQUEST']._serialized_start=129
  _globals['_CALLECHOREQUEST']._serialized_end=159
  _globals['_CALLECHORESPONSE']._serialized_start=161
  _globals['_CALLECHORESPONSE']._serialized_end=263
  _globals['_HEALTHSERVICE']._serialized_start=265
  _globals['_HEALTHSERVICE']._serialized_end=332
  _globals['_ECHOSERVICE']._serialized_start=334
  _globals['_ECHOSERVICE']._serialized_end=394
  _globals['_CALLECHOSERVICE']._serialized_start=396
  _globals['_CALLECHOSERVICE']._serialized_end=472
# @@protoc_insertion_point(module_scope)
